dist: xenial
language: python
python:
  "3.7-dev"
services:
  - postgresql

before_script:
  - createdb TEMPLATE

install:
  - pip install pipenv
  - pipenv install --dev

script:
  - pipenv run pytest
