service: mypythonservice

plugins:
  - serverless-python-requirements
  - serverless-pseudo-parameters

custom:
  pythonRequirements:
    dockerizePip: false
    slim: true
    useDownloadCache: true
    useStaticCache: true
    noDeploy:
      - psycopg2

provider:
  name: aws
  runtime: python3.7
  stage: ${opt:stage, 'dev'}
  region: eu-central-1

  iamRoleStatements:
    - Effect: Allow
      Action: secretsmanager:GetSecretValue
      Resource: "arn:aws:secretsmanager:#{AWS::Region}:#{AWS::AccountId}:secret:myservice/*"

package:
  exclude:
    - node_modules/**
    - venv/**
    - '**/__pycache__/**'
    - ".#*"

functions:
  hello:
    memorySize: 128
    handler: handler.hello
    events:
      - http: POST /hello
