Conditions:
  BastionEnabled: !Not [!Equals ["${self:custom.bastion.sshKeyPairName}", ""]]

Mappings:
  AWSAMIRegionMap:
    AMI:
      AMZNLINUXHVM: amzn-ami-hvm-2018.03.0.20180811-x86_64-gp2
    ap-northeast-1:
      AMZNLINUXHVM: ami-06cd52961ce9f0d85
    ap-northeast-2:
      AMZNLINUXHVM: ami-0a10b2721688ce9d2
    ap-south-1:
      AMZNLINUXHVM: ami-0912f71e06545ad88
    ap-southeast-1:
      AMZNLINUXHVM: ami-08569b978cc4dfa10
    ap-southeast-2:
      AMZNLINUXHVM: ami-09b42976632b27e9b
    ca-central-1:
      AMZNLINUXHVM: ami-0b18956f
    eu-central-1:
      AMZNLINUXHVM: ami-0233214e13e500f77
    eu-west-1:
      AMZNLINUXHVM: ami-047bb4163c506cd98
    eu-west-2:
      AMZNLINUXHVM: ami-f976839e
    eu-west-3:
      AMZNLINUXHVM: ami-0ebc281c20e89ba4b
    sa-east-1:
      AMZNLINUXHVM: ami-07b14488da8ea02a0
    us-east-1:
      AMZNLINUXHVM: ami-0ff8a91507f77f867
    us-east-2:
      AMZNLINUXHVM: ami-0b59bfac6be064b78
    us-west-1:
      AMZNLINUXHVM: ami-0bdb828fd58c52235
    us-west-2:
      AMZNLINUXHVM: ami-a0cfeed8

  LinuxAMINameMap:
    Amazon-Linux-HVM:
      Code: AMZNLINUXHVM

Resources:
  EC2SNSTopic:
    Type: AWS::SNS::Topic
    Condition: BastionEnabled
    Properties:
      Subscription:
      - Endpoint: ${self:custom.bastion.alertEmails}
        Protocol: email

  BastionMainLogGroup:
    Type: 'AWS::Logs::LogGroup'
    Condition: BastionEnabled
    Properties:
      RetentionInDays: ${self:custom.bastion.logRetentionInDays}

  SSHMetricFilter:
    Type: 'AWS::Logs::MetricFilter'
    Condition: BastionEnabled
    Properties:
      LogGroupName: !Ref BastionMainLogGroup
      FilterPattern: ON FROM USER PWD
      MetricTransformations:
        - MetricName: SSHCommandCount
          MetricValue: '1'
          MetricNamespace: "Bastion/#{AWS::StackName}"

  BastionSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Condition: BastionEnabled
    Properties:
      GroupDescription: '#{AWS::StackName}'
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: '0.0.0.0/0'
        - IpProtocol: icmp
          FromPort: -1
          ToPort: -1
          CidrIp: '0.0.0.0/0'
      Tags:
      - Key: Name
        Value: '#{AWS::StackName}-BastionSecurityGroup'

  BastionHostRole:
    Type: 'AWS::IAM::Role'
    Condition: BastionEnabled
    Properties:
      Policies:
        - PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - 's3:GetObject'
                Resource:
                  - 'arn:aws:s3:::ops.jetbridge.com/public/*'
                Effect: Allow
          PolicyName: jetbridge-ops-get-public-s3-policy
        - PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - 'logs:CreateLogStream'
                  - 'logs:GetLogEvents'
                  - 'logs:PutLogEvents'
                  - 'logs:DescribeLogGroups'
                  - 'logs:DescribeLogStreams'
                  - 'logs:PutRetentionPolicy'
                  - 'logs:PutMetricFilter'
                  - 'logs:CreateLogGroup'
                Resource:
                  - !Join [':', ['arn:aws:logs:#{AWS::Region}:#{AWS::AccountId}:log-group:', !Ref BastionMainLogGroup, '*']]
                Effect: Allow
          PolicyName: bastion-cloudwatch-logs-policy
        - PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - 'ec2:AssociateAddress'
                  - 'ec2:DescribeAddresses'
                Resource:
                  - '*'
                Effect: Allow
          PolicyName: bastion-eip-policy
      Path: /
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - 'sts:AssumeRole'
            Principal:
              Service:
                - ec2.amazonaws.com
            Effect: Allow
        Version: '2012-10-17'

  BastionHostProfile:
    Condition: BastionEnabled
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Roles:
        - !Ref BastionHostRole
      Path: /

  EIP:
    Condition: BastionEnabled
    Type: 'AWS::EC2::EIP'
    Properties:
      Domain: vpc

  BastionAutoScalingGroup:
    Condition: BastionEnabled
    Type: 'AWS::AutoScaling::AutoScalingGroup'
    Properties:
      DesiredCapacity: '1'
      LaunchConfigurationName: !Ref BastionLaunchConfiguration
      MaxSize: '1'
      MinSize: '1'
      Tags:
      - Key: Name
        Value: '#{AWS::StackName}-BastionHost'
        PropagateAtLaunch: true
      NotificationConfigurations:
      - TopicARN: !Ref EC2SNSTopic
        NotificationTypes:
        - 'autoscaling:EC2_INSTANCE_LAUNCH_ERROR'
        - 'autoscaling:EC2_INSTANCE_TERMINATE_ERROR'
      VPCZoneIdentifier:
        - !Ref PublicSubnetA
        - !Ref PublicSubnetB
        - !Ref PublicSubnetC
    CreationPolicy:
      ResourceSignal:
        Count: 1
        Timeout: PT10M
    UpdatePolicy:
      AutoScalingRollingUpdate:
        PauseTime: PT10M
        SuspendProcesses:
        - HealthCheck
        - ReplaceUnhealthy
        - AZRebalance
        - AlarmNotification
        - ScheduledActions
        WaitOnResourceSignals: true

  BastionLaunchConfiguration:
    Condition: BastionEnabled
    Type: 'AWS::AutoScaling::LaunchConfiguration'
    Metadata:
      'AWS::CloudFormation::Authentication':
        S3AccessCreds:
          type: S3
          roleName: !Ref BastionHostRole
          buckets:
            - "ops.jetbridge.com"
      'AWS::CloudFormation::Init':
        config:
          files:
            /tmp/bastion_bootstrap.sh:
              source: "${self:custom.bastion.bootstrap}"
              mode: '000550'
              owner: root
              group: root
              authentication: S3AccessCreds
            /home/ec2-user/.psqlrc:
              content: |
                \set PROMPT1 '%[%033[1;31m%]%M%[%033[0m%]:%> %[%033[1;33m%]%n%[%033[0m%]@%/%R%#%x '
                \pset pager off
                \set COMP_KEYWORD_CASE upper
                \set VERBOSITY verbose
                \set HISTCONTROL ignorespace
                \set HISTFILE ~/.psql_history- :DBNAME
                \set HISTSIZE 5000
                \set version 'SELECT version();'
                \set extensions 'select * from pg_available_extensions;'
              mode: "000644"
              owner: "root"
              group: "root"
          commands:
            b-bootstrap:
              command: !Join
                - ''
                - - ./tmp/bastion_bootstrap.sh
                  - ' --banner ${self:custom.bastion.banner}'
                  - ' --enable ${self:custom.bastion.bannerEnabled}'
                  - ' --tcp-forwarding ${self:custom.bastion.tcpForwardingEnabled}'
                  - ' --x11-forwarding ${self:custom.bastion.x11ForwardingEnabled}'
    Properties:
      AssociatePublicIpAddress: true
      PlacementTenancy: ${self:custom.bastion.tenancy}
      KeyName: ${self:custom.bastion.sshKeyPairName}
      IamInstanceProfile: !Ref BastionHostProfile
      ImageId: !FindInMap
        - AWSAMIRegionMap
        - !Ref 'AWS::Region'
        - !FindInMap
          - LinuxAMINameMap
          - 'Amazon-Linux-HVM'
          - Code
      SecurityGroups:
        - !Ref BastionSecurityGroup
      InstanceType: ${self:custom.bastion.instanceType}
      UserData: !Base64
        'Fn::Join':
          - ''
          - - |
              #!/bin/bash
            - |
              set -x
            - |
              export PATH=$PATH:/usr/local/bin
            - |
              which pip &> /dev/null
            - |
              if [ $? -ne 0 ] ; then
            - |2
                  echo "PIP NOT INSTALLED"
            - |2
                  [ `which yum` ] && $(yum install -y epel-release; yum install -y python-pip) && echo "PIP INSTALLED"
            - |2
                  [ `which apt-get` ] && apt-get -y update && apt-get -y install python-pip && echo "PIP INSTALLED"
            - |
              fi
            - |
              pip install --upgrade pip &> /dev/null
            - |
              pip install awscli --ignore-installed six &> /dev/null
            - >
              easy_install
              https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz
            - |
              yum install -y postgresql96 &> /dev/null
            - EIP_LIST="
            - !Ref EIP
            - |
              "
            - CLOUDWATCHGROUP=
            - !Ref BastionMainLogGroup
            - |+

            - 'cfn-init -v --stack '
            - !Ref 'AWS::StackName'
            - ' --resource BastionLaunchConfiguration --region '
            - !Ref 'AWS::Region'
            - |+

            - 'cfn-signal -e $? --stack '
            - !Ref 'AWS::StackName'
            - ' --resource BastionAutoScalingGroup --region '
            - !Ref 'AWS::Region'
            - |+

  CPUTooHighAlarm:
    Type: 'AWS::CloudWatch::Alarm'
    Condition: BastionEnabled
    Properties:
      AlarmDescription: 'Average CPU utilization over last 10 minutes higher than 80%'
      Namespace: 'AWS/EC2'
      MetricName: CPUUtilization
      Statistic: Average
      Period: 600
      EvaluationPeriods: 1
      ComparisonOperator: GreaterThanThreshold
      Threshold: 80
      AlarmActions:
      - Ref: EC2SNSTopic
      Dimensions:
      - Name: AutoScalingGroupName
        Value: !Ref BastionAutoScalingGroup

Outputs:
  EIP:
    Condition: BastionEnabled
    Description: The public IP address of the SSH bastion host/instance
    Value: !Ref EIP
    Export:
      Name: '#{AWS::StackName}-EIP'

  SSHCommand:
    Description: SSH command line
    Condition: BastionEnabled
    Value: !Join
             - ''
             - - 'ssh -i "'
               - '~/.ssh/'
               - ${self:custom.bastion.sshKeyPairName}
               - '.pem" '
               - 'ec2-user@'
               - !Ref EIP

  PSQLCommand:
    Description: psql command line
    Condition: BastionEnabled
    Value: !Join
             - ''
             - - 'psql -h '
               - !GetAtt DBCluster.Endpoint.Address
               - ' -p '
               - !GetAtt DBCluster.Endpoint.Port
               - ' -U dbadmin '
               - ${self:custom.db.dbname}
