Conditions:
  IsProd: !Equals ["${self:provider.stage}", "prod"]

Resources:
  # DB
  DBCluster:
    Type: AWS::RDS::DBInstance
    Properties:
      DeletionProtection: !If [IsProd, true, false]
      PubliclyAccessible: true  # change depending on bastion config
      EnablePerformanceInsights: true
      Engine: Postgres
      DBName: ${self:custom.db.dbname}
      DBInstanceIdentifier: "#{AWS::StackName}"
      MasterUsername: !Join ['', ['{{resolve:secretsmanager:', !Ref RDSInstanceSecret, ':SecretString:username}}' ]]
      MasterUserPassword: !Join ['', ['{{resolve:secretsmanager:', !Ref RDSInstanceSecret, ':SecretString:password}}' ]]
      DBInstanceClass: ${self:custom.db.instance_class}
      AllocatedStorage: ${self:custom.db.storage}
      VPCSecurityGroups:
      - "Fn::GetAtt": DBSecurityGroup.GroupId
      DBSubnetGroupName: !Ref DBSubnetGroup

  # DB login secret
  RDSInstanceSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: 'RDS master admin'
      Name: ${self:custom.secrets.rds.credentials}
      GenerateSecretString:
        SecretStringTemplate: '{"username": "dbadmin"}'
        GenerateStringKey: 'password'
        PasswordLength: 16
        ExcludeCharacters: '"@/\%:\\;'
  # our RDS instance secret in the form of a DSN connection string
  RDSURLSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: 'RDS DATABASE_URL'
      Name: ${self:custom.secrets.rds.url}
      SecretString:
        "Fn::Join": ['', ['{"DATABASE_URL": "', 'postgresql://', {"Fn::Join": ['', ['{{resolve:secretsmanager:', !Ref RDSInstanceSecret, ':SecretString:username}}']]}, ':', {"Fn::Join": ['', ['{{resolve:secretsmanager:', !Ref RDSInstanceSecret, ':SecretString:password}}']]}, '@',{ "Fn::Join": [":", ["Fn::GetAtt": [DBCluster, Endpoint.Address], "Fn::GetAtt": [DBCluster, Endpoint.Port]]] }, "/${self:custom.db.dbname}", '"}']]

  SecretRDSInstanceAttachment:
    Type: AWS::SecretsManager::SecretTargetAttachment
    Properties:
      SecretId:
        Ref: RDSInstanceSecret
      TargetId:
        Ref: DBCluster
      TargetType: AWS::RDS::DBInstance
