name: Python application

on: [push]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      # environment
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - uses: harmon758/postgresql-action@v1
        with:
          postgresql version: 11
      - uses: dschep/install-poetry-action@v1.3
      - name: "Install dependencies"
        run: poetry install -n --no-ansi
      - name: "Check formatting: black"
        uses: lgeiger/black-action@master
        with:
          args: ". --check"
      - name: "Lint: flake8"
        run: flake8 . --count --show-source --statistics
      - name: "Test: pytest"
        run: pytest
        env:
          TEST_DATABASE_URL: "postgresql://postgres@postgres/pytest"
      - name: "Type checks: mypy"
        uses: jpetrucciani/mypy-check@master
