name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      # environment
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - uses: harmon758/postgresql-action@v1
        with:
          postgresql version: 11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip pipenv
          pipenv install --deploy --dev

      # checks
      - name: "Check formatting: black"
        uses: lgeiger/black-action@master
        with:
          args: ". --check"
      - name: "Lint: flake8"
        run: |
          pipenv run flake8 . --count --show-source --statistics
      - name: "Test: pytest"
        run: |
          pipenv run pytest
        env:
          TEST_DATABASE_URL: "postgresql://postgres@localhost/pytest"
      - name: "Type checks: mypy"
        uses: jpetrucciani/mypy-check@master
